betfair_client:
  env_file: ".env"
  required_credentials: ["USER_NAME", "PASSWORD", "APP_KEY"]

storage:
  data: "data"
  temp: "data/temp"

mapping:
  mapping_dir: "mappings"
  active_files: ["scotland.json"]
  tournament_country_map:
    "1": "GB"   # English Premier League
    "54": "GB"  # Scottish Premiership
    "55": "GB"  # Scottish Championship

search:
  primary_strategy: "ExactDateTeamSearch"
  extended_strategy: "ExtendDateTeamSearch" # null for none

  exact_date_team_search:
    day: 1
    minute: 0
    hour: 0

  # TODO: Missing some searches 
  extended_strategy_conf:
    day: 30
    minute: 0
    hour: 0



betfair_football:
  sport: "Soccer"
  plan: "Basic Plan"
  file_type: ["M"]
  markets: [
    # Half-time markets
      "FIRST_HALF_GOALS_05",
      "FIRST_HALF_GOALS_15",
      "FIRST_HALF_GOALS_25",
      # "HALF_TIME_SCORE",
      "HALF_TIME",
    # Full-time markets
      "OVER_UNDER_05",
      "OVER_UNDER_15",
      "OVER_UNDER_25",
      "OVER_UNDER_35",
      "CORRECT_SCORE", # TODO:
            #   "CORRECT_SCORE2",
      "MATCH_ODDS",
      # "BOTH_TEAMS_TO_SCORE",
            ]


processing: # Extractor
  clean_data: true
  pre_kickoff_mins: 10      # Data from 10 mins before kickoff
  post_kickoff_mins: 120     # Data up to 100 mins after kickoff  
  resample_to_mins: true     # Resample to 1-minute intervals
  clip_extreme_odds: true    # Remove unrealistic odds
  min_odds: 1.01
  max_odds: 1000
  implied_odds: false   # in _calcualte_derived_feature 
  odds_movements: false # in _calcualte_derived_feature 



