betfair_client:
  env_file: ".env"
  required_credentials: ["USER_NAME", "PASSWORD", "APP_KEY"]


search:
  primary_strategy: "ExactDateTeamSearch"
  extended_strategy:  null

  exact_date_team_search:
    day: 1
    minute: 0
    hour: 0

  extended_strategy_conf:
    day: 31
    minute: 0
    hour: 0



betfair_football:
  sport: "Soccer"
  plan: "Basic Plan"
  file_type: ["M"]
  markets: [
    # Half-time markets
      "FIRST_HALF_GOALS_05",
      "FIRST_HALF_GOALS_15",
      "FIRST_HALF_GOALS_25",
      "HALF_TIME_SCORE",
      "HALF_TIME",
    # Full-time markets
#      "OVER_UNDER",
      "OVER_UNDER_05",
      "OVER_UNDER_15",
      "OVER_UNDER_25",
      "OVER_UNDER_35",
      "CORRECT_SCORE",
            #   "CORRECT_SCORE2",
      "MATCH_ODDS",
      "BOTH_TEAMS_TO_SCORE",
            ]
