betfair_client:
  env_file: ".env"
  required_credentials: ["USER_NAME", "PASSWORD", "APP_KEY"]


mapping:
  mapping_dir: "mappings"
  active_files: ["scotland.json"]
  tournament_country_map:
    "1": "GB"   # English Premier League
    "54": "GB"  # Scottish Premiership
    "55": "GB"  # Scottish Championship

grabber:
  threaded: true #if the processing is thread
  max_number_of_workers: 14
  checkpoint_interval: 100


search:
  primary_strategy: "ExactDateTeamSearch"
  extended_strategy: "ExtendDateTeamSearch" # null for none

  exact_date_team_search:
    day: 2
    minute: 0
    hour: 0

  # TODO: Missing some searches 
  extended_strategy_conf:
    day: 30
    minute: 0
    hour: 0

betfair_football:
  sport: "Soccer"
  plan: "Basic Plan"
  file_type: ["M"]
  markets: [
    # Half-time markets
       "HALF_TIME",
       "FIRST_HALF_GOALS_05",
       "FIRST_HALF_GOALS_15",
       "FIRST_HALF_GOALS_25",
       "HALF_TIME_SCORE",
  #### Full-time markets
      "MATCH_ODDS",
      "OVER_UNDER_05",
      "OVER_UNDER_15",
      "OVER_UNDER_25",
      "OVER_UNDER_35",
      "CORRECT_SCORE", 
      "BOTH_TEAMS_TO_SCORE",
            ]

betfair_downloader:
  max_auth_attempts: 3
  error_file_size: 500 # less than 1KB
  max_retries: 3  # Number of main retry cycles
  html_retries: 8  # Number of 302 retries per main cycle  
  html_sleep_before_retry: 1  # Sleep between retries

processing: # Extractor
  clean_data: true
  pre_kickoff_mins: 30      # Data from 10 mins before kickoff
  post_kickoff_mins: 120     # Data up to 100 mins after kickoff  
  apply_forward_fill: false  # apppy ffill or not - ltp 
  resample_to_mins: true     # Resample to 1-minute intervals
  clip_extreme_odds: true    # Remove unrealistic odds
  min_odds: 1.01
  max_odds: 1000
  implied_odds: false   # in _calcualte_derived_feature 
  odds_movements: false # in _calcualte_derived_feature 

  # HACK:
storage:
  data: "data"
  temp: "data/temp"
