# src/whatstheodds/configs/setting.yaml
database:
  url: "postgresql://admin:supersecretpassword@192.168.1.88:5432/sofascrape_db"

betfair_client:
  env_file: ".env"
  required_credentials: ["USER_NAME", "PASSWORD", "APP_KEY"]

storage:
  data: "data"
  temp: "data/temp"

mapping:
  mapping_dir: "mappings"
  active_files: ["scotland.json", "england.json", "ireland.json"]
  tournament_country_map:
    "1": "GB"   # English Premier League
    "2": "GB"   # English Championship
    "3": "GB"   # English League one
    "84": "GB"  # English League two
    "54": "GB"  # Scottish Premiership
    "55": "GB"  # Scottish Championship
    "79": "IE"  # Ireland Premier
    "718": "IE" # Ireland First Div

betfair_rate_limit:
  max_request: 99 # max 100 
  time_window: 10 # time seconds

search:
  primary_strategy: "ExactDateTeamSearch"
  extended_strategy: "ExtendDateTeamSearch" # null for none
  exact_date_team_search:
    day: 1
    minute: 0
    hour: 0
  extended_strategy_conf:
    day: 30
    minute: 0
    hour: 0

betfair_downloader:
  max_auth_attempts: 3
  error_file_size: 500 # less than 1KB
  max_retries: 3  # Number of main retry cycles
  html_retries: 8  # Number of 302 retries per main cycle  
  html_sleep_before_retry: 1  # Sleep between retries
  track_market_failures: true
  skip_existing_downloads: true
  selective_retry_enabled: true

betfair_football:
  sport: "Soccer"
  plan: "Basic Plan"
  file_type: ["M"]
  markets: [
      "MATCH_ODDS",
      "OVER_UNDER_05",
      "OVER_UNDER_15",
      "OVER_UNDER_25",
      "OVER_UNDER_35",
      "OVER_UNDER_45",
      "OVER_UNDER_55",
      "CORRECT_SCORE", 
      "BOTH_TEAMS_TO_SCORE"
  ]

processing:
  clean_data: true
  pre_kickoff_mins: 10      # Data from 10 mins before kickoff
  post_kickoff_mins: 120     # Data up to 120 mins after kickoff  
  apply_forward_fill: false  # apppy ffill or not - ltp 
  resample_to_mins: true     # Resample to 1-minute intervals
  clip_extreme_odds: true    # Remove unrealistic odds
  min_odds: 1.01
  max_odds: 1000.0
  implied_odds: false   
  odds_movements: false 

processor:
  output_dir: "/home/james/bet_project/"

max_workers:
  search: 1
  download: 5
